// This file will be auto-generated by Supabase CLI
// For now, we'll define a basic type structure

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          username: string;
          email: string;
          phone_number: string | null;
          user_type: string;
          verified_status: string;
          created_at: string;
          updated_at: string;
          last_login: string | null;
        };
        Insert: {
          id: string;
          username: string;
          email: string;
          phone_number?: string | null;
          user_type?: string;
          verified_status?: string;
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
        };
        Update: {
          id?: string;
          username?: string;
          email?: string;
          phone_number?: string | null;
          user_type?: string;
          verified_status?: string;
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
        };
      };
      // Add other table definitions as needed
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}